apiVersion: 1

datasources:
  # InfluxDB v2 Data Source (Flux) - For Energy Data
  - name: InfluxDB_Raw
    uid: influxdb_raw
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: Ennergy
      defaultBucket: AI205_raw
      tlsSkipVerify: true
    secureJsonData:
      token: rft_M6WkVq5f48jzITJTVjDLR1wdvSUiThfVP4PH4LIZi6PgiZjUtfiVo7_KItFRYe4yzpwssxuO9VXUzhUFuQ==
    isDefault: true

  # MySQL Data Source - For User & Audit Logs (Backup Database)
  - name: SmartEnergy_MySQL
    uid: mysql_main
    type: mysql
    url: 127.0.0.1:3306
    database: AI205
    user: root
    secureJsonData:
      password: Nontawat01
